name: dax
author: Goutte <antoine@goutenoir.com>
description: Experimental framework for developing WebGL-enabled applications.
version: 0.2.1
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
#  browser: any  # pretty sure we do not need this anymore, investigate

  # Added some code to vector_math. Not much, and might be PR'ed some day.
  # That lib needs a lot more work, and maybe some more memory-friendly APIs,
  # like glmatrix provides. (by providing out)
  # Besides, thanks to tree-shaking, we can make a bigass math lib with everything.
  #vector_math: '>=1.4.2+1 <2.0.0'
  vector_math:
    git:
      ref: master
      url: https://github.com/Goutte/vector_math

  # for (int i in range(0,10))
#  range: '>=1.1.0 <2.0.0'
  range:
    git:
      ref: master
      url: https://github.com/ilyakharlamov/dart-range

  # Incomplete color management
  color: '>=0.3.1 <1.0.0'
  # Good for development only, FPS stats
  stats: '>=0.1.2 <1.0.0'
  # Still pretty unsure about : using this / a fork of it / rollin our own
  game_loop:
      git: https://github.com/johnmccutchan/game_loop.git
dev_dependencies:
  unittest: '>=0.9.0 <1.0.0'